---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: home
  name: home
spec:
  volumes:
  - name: www-content
    emptyDir: {}
  initContainers:
  - name: init-service
    image: busybox:1.28
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: www-content
    command: ['sh', '-c', 'cd /usr/share/nginx/html; echo "<HTML><HEAD><TITLE>Welcome to our Home page!</TITLE></HEAD><BODY BGCOLOR="FFFFFF"><CENTER><IMG SRC="https://animalcrossingworld.com/wp-content/uploads/2020/05/animal-crossing-new-horizons-guide-villager-house-exterior-al-trim.png" ALIGN="BOTTOM"></CENTER><HR><a href="http://my-store-demo.click/">Home...</a>Return to Home Page<HR><a href="http://my-store-demo.click/store">Store...</a>Go to Main Store...<HR><a href="http://my-store-demo.click/cart">Cart...</a>Review your Cart<H1>For Sale</H1><H2>Amazing Products</H2><HR></BODY></HTML>" > index.html']
  containers:
  - image: nginx
    name: home
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: www-content
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: home
  name: home
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: home
  type: ClusterIP

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: cart
  name: cart
spec:
  volumes:
  - name: www-content
    emptyDir: {}
  initContainers:
  - name: init-service
    image: busybox:1.28
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: www-content
    command: ['sh', '-c', 'cd /usr/share/nginx/html; echo "<HTML><HEAD><TITLE>Your Car Section</TITLE></HEAD><BODY BGCOLOR="FFFFFF"><CENTER><IMG SRC="https://www.nicepng.com/png/full/217-2175038_caddy-trolley-caddie-basket-buy-buying-cart-online.png" ALIGN="BOTTOM"></CENTER><HR><a href="http://my-store-demo.click/">Home...</a>Return to Home Page<H1>For Sale</H1><H2>Amazing Products</H2><HR></BODY></HTML>" > index.html']
  containers:
  - image: nginx
    name: cart
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: www-content
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: cart
  name: cart
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: cart
  type: ClusterIP

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: store
  name: store
spec:
  volumes:
  - name: www-content
    emptyDir: {}
  initContainers:
  - name: init-service
    image: busybox:1.28
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: www-content
    command: ['sh', '-c', 'cd /usr/share/nginx/html; echo "<HTML><HEAD><TITLE>Store Section</TITLE></HEAD><BODY BGCOLOR="FFFFFF"><CENTER><IMG SRC="https://www.definicionabc.com/wp-content/uploads/tecnologia/App-Store.jpg" ALIGN="BOTTOM"></CENTER><HR><a href="http://my-store-demo.click/">Home...</a>Return to Home Page<H1>For Sale</H1><H2>Amazing Products</H2><HR></BODY></HTML>" > index.html']
  containers:
  - image: nginx
    name: store
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: www-content
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: store
  name: store
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: store
  type: ClusterIP

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: page404
  name: page404
spec:
  volumes:
  - name: www-content
    emptyDir: {}
  initContainers:
  - name: init-service
    image: busybox:1.28
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: www-content
    command: ['sh', '-c', 'cd /usr/share/nginx/html; echo "<HTML><HEAD><TITLE>Seems that you are lost!</TITLE></HEAD><BODY BGCOLOR="FFFFFF"><CENTER><IMG SRC="https://freefrontend.com/assets/img/html-funny-404-pages/HTML-404-Crying-Baby-Page.png" ALIGN="BOTTOM"></CENTER><HR><a href="http://my-store-demo.click/">Home...</a>Return to Home Page<H1>For Sale</H1><H2>Amazing Products</H2><HR></BODY></HTML>" > index.html']
  containers:
  - image: nginx
    name: page404
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: www-content
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: page404
  name: page404
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: page404
  type: ClusterIP

