apiVersion: v1
kind: Pod
metadata:
  labels:
    run: home
  name: home
spec:
  volumes:
  - name: www-content
    emptyDir: {}
  initContainers:
  - name: init-service
    image: busybox:1.28
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: www-content
    command: ['sh', '-c', 'cd /usr/share/nginx/html; echo "<HTML><HEAD><TITLE>Welcome to our Home page!</TITLE></HEAD><BODY BGCOLOR="FFFFFF"><CENTER><IMG SRC="https://animalcrossingworld.com/wp-content/uploads/2020/05/animal-crossing-new-horizons-guide-villager-house-exterior-al-trim.png" ALIGN="BOTTOM"></CENTER><HR><a href="http://my-store-demo.click/">Home...</a>Return to Home Page<HR><a href="http://my-store-demo.click/store">Store...</a>Go to Main Store...<HR><a href="http://my-store-demo.click/cart">Cart...</a>Review your Cart<H1>For Sale</H1><H2>Amazing Products</H2><HR></BODY></HTML>" > index.html']
  containers:
  - image: nginx
    name: home
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: www-content
